
import curses
import os
import webbrowser

stations = [(
             "Groove Salad",
             "A nicely chilled plate of ambient/downtempo beats and grooves.",
             "http://uwstream1.somafm.com:80"),
            ("Secret Agent",
             "The soundtrack for your stylish, mysterious, dangerous life. For Spies and PIs too!",
             "http://xstream1.somafm.com:8002"),
            ("Drone Zone",
             "Served best chilled, safe with most medications. Atmospheric textures with minimal beats.",
             "http://uwstream2.somafm.com:80"),
            ("Indie Pop Rocks!",
             "New and classic favorite indie pop tracks.",
             "http://xstream1.somafm.com:8090"),
            ("Cliqhop IDM",
             "Blips'n'beeps backed mostly w/beats. Intelligent Dance Music.",
             "http://xstream1.somafm.com:8062"),
            ("Beat Blender",
             "A late night blend of deep-house and downtempo chill.",
             "http://xstream1.somafm.com:8388"),
            ("The Trip",
             "Progressive house / trance. Tip top tunes.",
             "http://xstream1.somafm.com:2504"),
            ("Illinois Street Lounge",
             "Classic bachelor pad, playful exotica and vintage music of tomorrow.",
             "http://xstream1.somafm.com:8500"),
            ("Space Station Soma",
             "Tune in, turn on, space out. Spaced-out ambient and mid-tempo electronica.",
             "http://xstream1.somafm.com:8000"),
            ("Doomed",
             "Dark industrial/ambient music for tortured souls.",
             "http://xstream1.somafm.com:8300"),
            ("Boot Liquor",
             "Americana Roots music for Cowhands, Cowpokes and Cowtippers.",
             "http://xstream1.somafm.com:7000"),
            ("Lush",
             "Sensuous and mellow vocals, mostly female, with an electronic influence.",
             "http://xstream1.somafm.com:8800"),
            ("Digitalis",
             "Digitally affected analog rock to calm the agitated heart.",
             "http://xstream1.somafm.com:8900"),
            ("Suburbs of Goa",
             "Desi-influenced Asian world beats and beyond.",
             "http://xstream1.somafm.com:8850"),
            ("Underground 80s",
             "Early 80s UK Synthpop and a bit of New Wave.",
             "http://xstream1.somafm.com:8884"),
            ("Sonic Universe",
             "Transcending the world of jazz with eclectic, avant-garde takes on tradition.",
             "http://uwstream2.somafm.com:8604"),
            ("PopTron",
             "Electropop and indie dance rock with sparkle and pop.",
             "http://xstream1.somafm.com:2200"),
            ("Covers",
             "Just covers. Songs you know by artists you don't. We've got you covered.",
             "http://xstream1.somafm.com:8700"),
            ("Black Rock FM",
             "From the Playa to the world, for the 2014 Burning Man festival.",
             "http://xstream1.somafm.com:8040"),
            ("Mission Control",
             "Celebrating NASA and Space Explorers everywhere.",
             "http://xstream1.somafm.com:2020"),
            ("BAGeL Radio",
             "What alternative rock radio should sound like.",
             "http://xstream1.somafm.com:9090"),
            ("South by Soma",
             "Music from bands who will be performing at SXSW, one of the biggest and best music festivals in the world. [explicit]",
             "http://uwstream2.somafm.com:5500"),
            ("Iceland Airwaves",
             "Music from bands who will be performing at Iceland Airwaves [explicit]",
             "http://uwstream2.somafm.com:5400"),
            ("SF 10-33",
             "Ambient music mixed with the sounds of San Francisco public safety radio traffic.",
             "http://uwstream2.somafm.com:2040"),
            ("Dub Step Beyond",
             "Dubstep, Dub and Deep Bass. May damage speakers at high volume.",
             "http://uwstream2.somafm.com:8400"),
            ("Folk Forward",
             "Indie Folk, Alt-folk and the occasional folk classics.",
             "http://xstream1.somafm.com:7400"),
            ("DEF CON Radio",
             "Music for Hacking. The DEF CON Year-Round Channel.",
             "http://xstream1.somafm.com:6200"),
            ("Earwaves",
             "Spanning the history of electronic and experimental music from the early pioneers to the latest innovators.",
             "http://xstream1.somafm.com:5100"),
            ("Deep Space One",
             "Deep ambient electronic, experimental and space music. A soundtrack for inner and outer space exploration.",
             "http://xstream1.somafm.com:2800"),
            ("Xmas in Frisko",
             "SomaFM's wacky and eclectic holiday mix. Not for the easily offended.",
             "http://xstream1.somafm.com:2100"),
            ("Christmas Lounge",
             "Chilled holiday grooves and classic winter lounge tracks. (Kid and Parent safe!)",
             "http://uwstream2.somafm.com:8000"),
            ("Christmas Rocks!",
             "Have your self an indie/alternative holiday season!",
             "http://xstream1.somafm.com:6100"),
            ("Seven Inch Soul",
             "Vintage soul tracks from the original 45 RPM vinyl.",
             "http://uwstream2.somafm.com:7770")]

for station, description, streamURL in sorted(stations):
    print '{0:<25}{1}'.format(station, description)
